### ISSUE TITLE
Add a Feature

### ISSUE THREAD

**Issue by abdelkrimkr** [alexmamo/FirestoreCleanArchitectureApp#2]
can you add this

when you click to a book item it was open edit page

also add when you click to fab you open an edit page but empty and add new book

to BookScreen
I want This help me!!

**Comment by abdelkrimkr** [comment]
@alexmamo

**Comment by AlexMamo** [comment]
This repo corresponds to a written article, so I cannot add more functionalities. I wanted to keep things simple. However, all those functionalities that you are looking for are already present in this [article](https://medium.com/firebase-tips-tricks/how-to-read-data-from-room-using-kotlin-flow-in-jetpack-compose-7a720dec35f5), which obviously has a [repo](https://github.com/alexmamo/RoomJetpackCompose) and a [video](https://www.youtube.com/watch?v=BIMSsgyGBKE).
