### ISSUE TITLE
Firebase functions with Dispatcher.IO?

### ISSUE THREAD

**Issue by Veisy** [alexmamo/FirestoreCleanArchitectureApp#3]
Hi @alexmamo, thank you for this sample app.
Shouldn't we call Firebase functions with Dispatcher.IO inside the ViewModel?
Have a nice day.

**Comment by alexmamo** [comment]
Hey @Veisy 
viewModelScope is a CoroutineScope that is tied to your ViewModel. This basically means that when ViewModel has cleared coroutines inside that scope are canceled too, which is very important. Dispatchers.IO means that it will suspend the function call and it will run in the IO thread which is managed by Kotlin. So it makes more sense to use viewModelScope

**Comment by AlexMamo** [comment]
Hey @Veisy 

viewModelScope is a CoroutineScope that is tied to your ViewModel. This means that when ViewModel is cleared, the coroutines inside that scope are cleared too. Dispatchers.IO means that a suspend function will run on the IO thread which is managed by Kotlin.
All functions in this repo, are suspend functions. A suspend function doesn’t block the thread, it suspends the thread, so it is safe to call them from any context **without** specifying a dispatcher. So in this case I cannot see any reason why we should use a dispatcher, right?
